### ISSUE TITLE
Will usocket support unix domain socket?

### ISSUE THREAD

**Issue by zhscn** [usocket/usocket#109]
Both SBCL and CCL support unix domain socket, it would be great usocket could provide a unified interface to eliminate differences between these implementations and platforms(windows supported domain socket since win10 1804).

**Comment by binghe** [comment]
Hi, you are welcome to contribute this new feature.

Speaking about Windows, once I wanted to use `AF_UNIX` (aka `AF_LOCAL`) in my application too. I think the correct statements is that "AF_UNIX is supported since Windows Insider build 17093" [1] only by a blog. By searching the latest documentation of Winsock2 [2], I don't think this feature is actually available (in main stream versions of Windows 10).

Chun

[1] https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/
[2] https://learn.microsoft.com/en-us/windows/win32/winsock/getting-started-with-winsock?redirectedfrom=MSDN

**Comment by binghe** [comment]
In practices, applications such as Docker Desktop still use named pipe on Windows while Unix domain sockets on all other platforms. This indicates that Windows actually doesn't support `AF_UNIX`, yet.

**Comment by zhscn** [comment]
> Hi, you are welcome to contribute this new feature.

Ok, I will try to implement it.

> This indicates that Windows actually doesn't support `AF_UNIX`, yet.

not really, it only supports the basic part of domain socket with these restricts:

> 
> - AF_UNIX datagram (SOCK_DGRAM) or sequence packet (SOCK_SEQPACKET) socket type. 
> - Ancillary data: Linux‘s unix socket implementation supports passing ancillary data such as passing file descriptors (`SCM_RIGHTS`) or credentials (‘SCM_CREDENTIALS`) over the socket. There is no support for ancillary data in the Windows unix socket implementation. 
> - Autobind feature (see the section on ‘sockaddr_un’ for details). 
> - socketpair: socketpair socket API is not supported in Winsock 2.0. 

The minimal example:

server:
```cpp
#include <WS2tcpip.h>
#include <WinSock2.h>
#include <Windows.h>
#include <afunix.h>
#include <iostream>

#define SOCK_PATH "D:\\domain.sock"

int main() {
  int result;
  WSADATA wsa_data{0};
  result = WSAStartup(MAKEWORD(2, 2), &wsa_data);
  if (result < 0) {
    std::cout << "WSAStartup failed\n";
    exit(0);
  }

  SOCKET listen_socket = INVALID_SOCKET;
  SOCKADDR_UN addr{0};

  listen_socket = socket(AF_UNIX, SOCK_STREAM, 0);
  if (listen_socket == INVALID_SOCKET) {
    std::cout << "socket failed " << WSAGetLastError() << '\n';
    exit(0);
  }
  addr.sun_family = AF_UNIX;
  strncpy_s(addr.sun_path, sizeof(addr.sun_path), SOCK_PATH,
            sizeof(SOCK_PATH) - 1);
  result = bind(listen_socket, (struct sockaddr *)&addr, sizeof(addr));
  if (result == SOCKET_ERROR) {
    std::cout << "bind failed " << WSAGetLastError() << '\n';
    exit(0);
  }

  result = listen(listen_socket, SOMAXCONN);
  if (result == SOCKET_ERROR) {
    std::cout << "listen failed " << WSAGetLastError() << '\n';
    exit(0);
  }

  SOCKET client_socket = accept(listen_socket, NULL, NULL);
  if (client_socket == INVALID_SOCKET) {
    std::cout << "accept failed " << WSAGetLastError() << '\n';
    exit(0);
  }

  char buffer[4096];
  memset(buffer, 0, 4096);
  recv(client_socket, buffer, 4096, 0);
  std::cout << buffer << '\n';
  closesocket(listen_socket);
  closesocket(client_socket);
  DeleteFileA(SOCK_PATH);
  WSACleanup();
  return 0;
}

```

client:
```cpp
#include <WS2tcpip.h>
#include <WinSock2.h>
#include <Windows.h>
#include <afunix.h>
#include <iostream>

#define SOCK_PATH "D:\\domain.sock"

int main() {
  int result;
  WSADATA wsa_data{0};
  result = WSAStartup(MAKEWORD(2, 2), &wsa_data);
  if (result < 0) {
    std::cout << "WSAStartup failed\n";
    exit(0);
  }

  SOCKET server_socket = INVALID_SOCKET;
  SOCKADDR_UN addr{0};

  server_socket = socket(AF_UNIX, SOCK_STREAM, 0);
  if (server_socket == INVALID_SOCKET) {
    std::cout << "socket failed " << WSAGetLastError() << '\n';
    exit(0);
  }
  addr.sun_family = AF_UNIX;
  strncpy_s(addr.sun_path, sizeof(addr.sun_path), SOCK_PATH,
            sizeof(SOCK_PATH) - 1);

  result = connect(server_socket, (struct sockaddr *)&addr,
                   sizeof(struct sockaddr_un));
  if (result < 0) {
    std::cout << "connect failed " << WSAGetLastError() << '\n';
    exit(0);
  }
  char buffer[] = "Hello domain socket!";
  send(server_socket, buffer, sizeof(buffer) - 1, 0);
  closesocket(server_socket);
  WSACleanup();
  return 0;
}

```

it should word on least windows and visual studio:
![](https://github.com/usocket/usocket/assets/45552541/4445d538-5a0f-4599-b1bd-9622702869bc)

**Comment by binghe** [comment]
OK, thanks for your sample code. I think I must have been testing it under VS 2015 but now I have VS 2019 and it indeeds compile your sample code correctly.

I don't think SBCL (or CCL) on Windows has already supported this new Windows feature (correct me if I'm wrong). But if we focus on Unix platforms, for now, this is indeed a possible new feature to be added to usocket. If you can make an initial contribution, even just for SBCL, I'll be happy to merge it and gradually improve the code base to support more CL platforms.
