### ISSUE TITLE
Version variable is not updated as of 0.8.6

### ISSUE THREAD

**Issue by phoe** [usocket/usocket#115]
https://github.com/usocket/usocket/blob/154be13cc667219cbe0a83b971d9f05d8f0aaea6/usocket.lisp#L17-L18

**Comment by binghe** [comment]
This version string is long obsoleted and the actual version is now stored in ASDF system definitions. So I'm going to use the following definition:
```
;; usocket version string, now stored in version.sexp file
(define-symbol-macro *version*
  #+asdf (asdf:system-version (asdf:find-system :usocket)) #-asdf "")
```
Let me know if there's any potential problems.

**Comment by binghe** [comment]
Should be `(asdf:component-version (asdf:find-system :usocket))` after testing on SBCL
