### ISSUE TITLE
NS-TRY-AGAIN-ERROR with wrong initargs

### ISSUE THREAD

**Issue by louis77** [usocket/usocket#121]
I'm using Lispworks 8.0.1 / Linux and occasionally get the following error:

```
The error 'MAKE-INSTANCE is called with keyword :SOCKET among the arguments (USOCKET:NS-TRY-AGAIN-ERROR
                                                                             :SOCKET
                                                                             #1=#<USOCKET:STREAM-USOCKET 4010274F33>
                                                                             :HOST-OR-IP
                                                                             NIL) which is not one of (:HOST-OR-IP).'
was raised while coercing (USOCKET:NS-TRY-AGAIN-ERROR
                           :SOCKET
                           #1#
                           :HOST-OR-IP
                           NIL) to a condition.
   [Condition of type CONDITIONS::COERCE-TO-CONDITION-ERROR]
```

When I inspect the NS-TRY-AGAIN-ERROR class, it appears that it only has 
`[ ]  POTENTIAL-INITARGS      = (:HOST-OR-IP)`.

The underlying condition NS-ERROR is defined as:

https://github.com/usocket/usocket/blob/2a97b5d5853b3a6e4375547364e3bdda137c4903/condition.lisp#L63-L68

There, the initarg socket is turned off for Lispworks. So I'm not sure why the condition is raised with the socket initarg, if that's a bug in usocket or if the feature switch should be removed?

**Comment by binghe** [comment]
Hi, thanks for your report. I checked the definition of `NS-ERROR` (parent condition of `NS-TRY-AGAIN-ERROR`) and found that the slot `SOCKET` was not defined for all backends. The commit [31b64f0](https://github.com/usocket/usocket/commit/31b64f010ef123061f3bf26f9efea62b14b3ea73) should have fixed this issue.

(If you are using usocket released versions, you need to manually checkout the `master` branch to have this fix immediately.)
