### ISSUE TITLE
add the library to Ultralisp project?

### ISSUE THREAD

**Issue by anranyicheng** [usocket/usocket#125]
The Quicklisp project is updated too slowly, and Utralisp is updated much faster. It's time to add usocket to the Utralisp project.
https://ultralisp.org/

**Comment by binghe** [comment]
Hi, I don't use ultralisp (never heard about it) but it seems good (just another dist of quicklisp). Anyway, I have just logged into ultralisp and added usocket. Let me know if you need anything else from me.

P.S. The standard Quicklisp dist doesn't find usocket from GitHub. Instead, it goes to usocket's official web site to download the release tarball.

**Comment by anranyicheng** [comment]
ok, thanks.
