### ISSUE TITLE
Export usocket get-host-name?

### ISSUE THREAD

**Issue by kilianmh** [usocket/usocket#128]
Some libraries use `get-host-name` from `usocket`. 
Should it be an exported symbol, or is it on purpose 
unexported (e.g. to avoid symbol-conflicts)?

**Comment by binghe** [comment]
Hi, why not using the exported `get-host-by-name`?

**Comment by binghe** [comment]
Sorry, I'm wrong. `get-host-name` returns hostname of the current machine, a different function.  I guess originally this function is not available for many backends, but I'm fine now to export it formally. Will do it soon (and then I think it's time to make a new release).

**Comment by kilianmh** [comment]
Thank you @binghe 
Fixed in f1f394971ff7545f5c3c2ef7d4e6532441b8a4af
