### ISSUE TITLE
Link to docs on front page is broken

### ISSUE THREAD

**Issue by rpgoldman** [usocket/usocket#132]
That link resolves to https://usocket.common-lisp.dev/ which gives a 404 error.

This may be an error at common-lisp.net, not a problem with the link itself.

**Comment by binghe** [comment]
The link is fine on my side. But the hostname is indeed obsoleted. If I update it to [this one](https://usocket.common-lisp.dev/api-docs.shtml), can you access it normally?

**Comment by rpgoldman** [comment]
That worked fine, thank you!

> The link is fine on my side. But the hostname is indeed obsoleted. If I update it to [this one](https://usocket.common-lisp.dev/api-docs.shtml), can you access it normally?

**Comment by binghe** [comment]
b3eb7a57
