### ISSUE TITLE
Symbol "INET6-SOCKET" not found in the SB-BSD-SOCKETS package.

### ISSUE THREAD

**Issue by fragrans** [usocket/usocket#16]
CL-USER> (ql:quickload :usocket)
To load "usocket":
  Load 1 ASDF system:
    usocket
; Loading "usocket"
[package usocket].......
; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "INET6-SOCKET" not found in the SB-BSD-SOCKETS package.
;   
;       Line: 287, Column: 71, File-Position: 10470
;   
;       Stream: #<SB-SYS:FD-STREAM
;                 for "file /home/ll/quicklisp/dists/quicklisp/software/usocket-0.6.4/backend/sbcl.lisp"
;                 {10049D1853}>

**Comment by hanshuebner** [comment]
What version of SBCL are you using, and on which platform?

**Comment by binghe** [comment]
Oh my … it must be an old version of SBCL which doesn’t contain IPv6 (< 1.2.5), and we should still support it … which means we need a patch to fix this in usocket 0.6.4.

Chun

**Comment by fragrans** [comment]
its 1.2.4.debian.

**Comment by binghe** [comment]
Hi there,

Can you place have a test on this patch (in attach)? I have changed some symbols (INET6-SOCKET and SOCKET-SHUTDOWN) from external to internal symbols. I think in this way you can get survive the compilation and those IPv6 code will actually not be used at all in your environment.

Regards,

Chun

**Comment by fragrans** [comment]
YES. PASSED.

**Comment by binghe** [comment]
Hi fragrans, thank you very much! I'll make a new patch release soon.
