### ISSUE TITLE
Error: Symbol "SOCKET-STREAM-SHUTDOWN" not found at all in the COMM package

### ISSUE THREAD

**Issue by RyanHope** [usocket/usocket#17]
Lispworks Personal 6.1 32bit build fails to load usocket

**Comment by binghe** [comment]
Hi Ryan,

I'm sorry about this issue, that symbol must be introduced in LispWorks
7.0. As a workaround, you need to replace the following method definition:

(defmethod socket-shutdown ((usocket stream-usocket) direction)
  (with-mapped-conditions (usocket)
    (comm::socket-stream-shutdown (socket usocket) direction)))

That is, replace "comm:socket-stream-shutdown" with
"comm::socket-stream-shutdown", this way the compilation of usocket will be
fine in LispWorks 6.1.  Of course, socket-shutdown API won't work in
LispWorks 6.1. I'll provide this facility for old versions of LispWorks in
another way, in future usocket updates.

Regards,

Chun Tian (binghe)


On 4 April 2016 at 02:25, Ryan Hope <notifications@github.com> wrote:

> Lispworks Personal 6.1 32bit build fails to load usocket
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/usocket/usocket/issues/17>
>



-- 
Chun Tian (binghe)
