### ISSUE TITLE
No tag for 0.6.4.1

### ISSUE THREAD

**Issue by eschaton** [usocket/usocket#20]
The commit for 0.6.4.1 should be tagged as such so it’s easy to compare changes against etc.

**Comment by binghe** [comment]
I added the tag. Thanks.

On 25 June 2016 at 19:25, Chris Hanson <notifications@github.com> wrote:

> The commit for 0.6.4.1 should be tagged as such so it’s easy to compare
> changes against etc.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/usocket/usocket/issues/20>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAJ-XdbGmQqZdIUHz8T8ehu5CyQtAla4ks5qPWRygaJpZM4I-Y_T>
> .
>



-- 
---

Chun Tian (binghe)
University of Bologna (Italy)
