### ISSUE TITLE
#-ecl #-ecl #-ecl

### ISSUE THREAD

**Issue by phoe-krk** [usocket/usocket#23]
https://github.com/usocket/usocket/blob/master/backend/sbcl.lisp#L181
```common-lisp
#-ecl #-ecl #-ecl
```

**`wat`**

**Comment by hanshuebner** [comment]
Missing problem description.

**Comment by phoe-krk** [comment]
Okay - if it isn't obvious.
```common-lisp
#-ecl #-ecl #-ecl
```
Why is `#-ecl` repeated three times in a row?
