### ISSUE TITLE
What happened to usocket:socket-server ?

### ISSUE THREAD

**Issue by ahungry** [usocket/usocket#34]
After a quicklisp update at some point, this function no longer exists?

This is a big backwards compatability break.

https://common-lisp.net/project/usocket/api-docs.shtml

**Comment by binghe** [comment]
Hi,

All server functions were moved to usocket-server system. If you package previously depends on only :usocket, now you can add :usocket-server to get those missing functions.

Sorry for the inconveniences, the purpose was to make core package smaller. 

Chun

Inviato da iPad

**Comment by ahungry** [comment]
No worries, thanks for the heads up and thanks for your work on usocket!

**Comment by digikar99** [comment]
This should perhaps be mentioned in the [documentation](https://common-lisp.net/project/usocket/api-docs.shtml) - or did I miss it?
