### ISSUE TITLE
usocket support for mezzano

### ISSUE THREAD

**Issue by ebrasca** [usocket/usocket#35]
Hi can you add support for mezzano?
Here link https://github.com/froggey/Mezzano

Thank you!

**Comment by ebrasca** [comment]
I have found there is usocket with mezzano suport.
Link https://github.com/froggey/usocket/blob/mezzano-port/backend/mezzano.lisp
Sory for my mistake.

**Comment by binghe** [comment]
Thanks for letting me know the Mezzano project...
