### ISSUE TITLE
Use of Portable-Threads in Usocket-Server

### ISSUE THREAD

**Issue by Shinmera** [usocket/usocket#36]
Hi, is there a particular reason that usocket-server uses portable-threads rather than bordeaux-threads? 

I'm mostly asking because portable-threads does not support Clasp and I'd like to run the test suite to test Clasp's usocket conformance that was patched in at https://github.com/clasp-developers/usocket .

**Comment by binghe** [comment]
Hi,

the choice of using portable-threads is just a personal preference. portable-threads package has much richer APIs than bordeaux-threads on supported platforms, but I didn’t use them at all.

The function SOCKET-SERVER only needs the ability to spawn a new thread (#'portable-threads:spawn-thread).  I don’t mind if you submit a patch for clasp backend and turn to depend on bordeaux-threads, which seems more popular these days.

—Chun

**Comment by Shinmera** [comment]
Thanks! I've replaced the calls with BT calls now and will submit a PR for the Clasp changes once all the tests pass.
