### ISSUE TITLE
WAIT-FOR-INPUT with READY-ONLY: return only one socket

### ISSUE THREAD

**Issue by phoe** [usocket/usocket#37]
Currently `WAIT-FOR-INPUT` with `READY-ONLY` argument conses up a new list every time.

I propose adding a new key that will tell `WAIT-FOR-INPUT` to return only the first socket that was detected as ready. This way, no consing will occur.

**Comment by binghe** [comment]
Hi,

thanks for your suggestion. Let me investigate if the consing can be prevented in single socket case.

—binghe

**Comment by binghe** [comment]
Hi,

in commit df1f86c11d1f597cb9debc6c7aa0a8ba84094a63, I did some optimization for `WAIT-FOR-INPUT` called with only one socket and `READY-ONLY`.  The idea is, now the consing only happens once, and a single-element wait-list is stored inside the socket object. When `WAIT-FOR-INPUT` is called again on the same (single) socket, no consing again.  (But if the socket is used in another `W-F-I` call with other sockets, its self wait-list will be overwritten, and new consing may occurs)

I hope you could make some tests and confirm if the latest usocket really resolves your issue.

Thanks,

Chun Tian

**Comment by binghe** [comment]
Let's temporarily close this issue and wait for further bug reports from you.
