### ISSUE TITLE
REDUCE #'MAX called with no arguments 

### ISSUE THREAD

**Issue by phoe** [usocket/usocket#38]
While testing my multithreaded application, I got the following error:
```common-lisp
invalid number of arguments: 0
   [Condition of type SB-INT:SIMPLE-PROGRAM-ERROR]

Restarts:
 0: [REPLACE-FUNCTION] Call a different function with the same arguments
 1: [CALL-FORM] Call a different form
 2: [RETRY] Abort the current iteration and send the acceptor back to its loop.
 3: [ABORT] abort thread (#<THREAD "Gateway - Acceptor for 127.0.0.1:41605" RUNNING {1005231EC3}>)

Backtrace:
  0: (MAX) [external]
      Locals:
        NIL = #<FUNCTION MAX>
        NIL = #<STANDARD-GENERIC-FUNCTION SB-BSD-SOCKETS:SOCKET-FILE-DESCRIPTOR (1)>
  1: (REDUCE #<FUNCTION MAX> NIL :KEY #<STANDARD-GENERIC-FUNCTION SB-BSD-SOCKETS:SOCKET-FILE-DESCRIPTOR (1)>)
      Locals:
        #:.DEFAULTING-TEMP. = #<STANDARD-GENERIC-FUNCTION SB-BSD-SOCKETS:SOCKET-FILE-DESCRIPTOR (1)>
        #:.DEFAULTING-TEMP.#1 = NIL
        #:.DEFAULTING-TEMP.#2 = 0
        #:.DEFAULTING-TEMP.#3 = NIL
        #:.DEFAULTING-TEMP.#4 = NIL
        FUNCTION = #<FUNCTION MAX>
        #:N-SUPPLIED-2 = NIL
        SEQUENCE = NIL
        SB-DEBUG::MORE = (:KEY #<STANDARD-GENERIC-FUNCTION SB-BSD-SOCKETS:SOCKET-FILE-DESCRIPTOR (1)>)
  2: (USOCKET::WAIT-FOR-INPUT-INTERNAL #S(USOCKET::WAIT-LIST :%WAIT NIL :WAITERS NIL :MAP #<HASH-TABLE :TEST EQL :COUNT 0 {1005364443}>) :TIMEOUT 0.001)
      Locals:
        #:.DEFAULTING-TEMP. = 0.001
        SOCKETS = #S(USOCKET::WAIT-LIST :%WAIT NIL :WAITERS NIL :MAP #<HASH-TABLE :TEST EQL :COUNT 0 {1005DF2DF3}>)
  3: (USOCKET:WAIT-FOR-INPUT #S(USOCKET::WAIT-LIST :%WAIT NIL :WAITERS NIL :MAP #<HASH-TABLE :TEST EQL :COUNT 0 {1005364443}>) :TIMEOUT 0.001 :READY-ONLY T)
      Locals:
        #:.DEFAULTING-TEMP. = 0.001
        #:.DEFAULTING-TEMP.#1 = T
        SOCKET-OR-SOCKETS = #S(USOCKET::WAIT-LIST :%WAIT NIL :WAITERS NIL :MAP #<HASH-TABLE :TEST EQL :COUNT 0 {1005DF2DF3}>)
  4: (USOCKET:WAIT-FOR-INPUT #<USOCKET:STREAM-SERVER-USOCKET {10052311D3}> :TIMEOUT 0.001 :READY-ONLY T)
      Locals:
        #:.DEFAULTING-TEMP. = 0.001
        #:.DEFAULTING-TEMP.#1 = T
        SOCKET-OR-SOCKETS = #<USOCKET:STREAM-SERVER-USOCKET {10052311D3}>
  ...
```
`REDUCE #'MAX` was called with an empty argument list, which is an error. There should be a check which asserts that the list is not empty.

I'm on SBCL 1.4.9 on Linux.

**Comment by binghe** [comment]
Hi,

thanks for the bug report. This should be the same issue in #19, where there was no backtraces to see.

It seems that, in multi-threading environments the function `WAIT-FOR-INPUT-INTERNAL` is not thread-safe: the current waiting `(wait-list-%wait sockets)` may be cleaned up by another call of the same function in another thread, causing `(reduce #'max ...)` failed on an empty list.

Could you please try if the attached patch solves your problem?

--Chun

[wait-for-input-internal.txt](https://github.com/usocket/usocket/files/2415069/wait-for-input-internal.txt)

**Comment by phoe** [comment]
I know why the bug happened - I was closing the server socket from thread A while thread B was operating on it. Socket operations are not thread-safe, so this is absolutely a case of PEBKAC.

I will nonetheless revert the change to my code (and introduce the thread-unsafe behavior) and test this patch tomorrow.

**Comment by binghe** [comment]
Let me close this issue for now, as the issue now seems clear with a possible workaround solution.

**Comment by phoe** [comment]
Yes. Sorry for my lack of reproduction; I've been spending my energy elsewhere and have nothing left for testing this. I'll try to fit it in on a more loose day.
