### ISSUE TITLE
Please export HOST-TO-HOSTNAME

### ISSUE THREAD

**Issue by phmarek** [usocket/usocket#42]
Because having a common function to convert a byte vector into a readable string would be very handy.

Thanks!

**Comment by binghe** [comment]
Alright, it will be exported in next version (0.8.0). Thanks for the suggestion.

**Comment by phmarek** [comment]
Would you please do a new release, so that QL uses a newer version? Thanks a lot!

**Comment by binghe** [comment]
I'm traveling, but I have created a new release tarball [1] such that Quicklisp will see and incorporate it for its next monthly release.  I'll announce this release in two days on usocket's mailing list (and PGP-sign the release tarball).

[1] https://common-lisp.net/project/usocket/releases/usocket-0.8.tar.gz

**Comment by binghe** [comment]
It seems that I'm a bit late for Quicklisp's February release.
