### ISSUE TITLE
Not receiving data after first tcp transmission SBCL Windows

### ISSUE THREAD

**Issue by Zulu-Inuoe** [usocket/usocket#43]
I hit an issue on usocket 0.7.1 on SBCL 1.4.12 and 1.4.14 on Windows (both 32 and 64-bit) where I had a relatively simple 'consume all data' loop like so:

```lisp
(loop
   :while (usocket:wait-for-input socket)
   :do (process-data (usocket:socket-stream socket)))
```

The first TCP packet coming in from the remote would come in fine, I would write a response, and the remote would receive it (Wireshark).
However, any data sent from the remote afterwards failed to wake up from `usocket:wait-for-input`.

I even tried switching to using `cl:listen` on the socket stream like so:

```lisp
(loop
   :with stream := (usocket:socket-stream socket)
   :if (listen stream)
     :do (process-data stream)
   :else
     :do (sleep +a-sufficient-amount-of-time+))
```

and experienced the same exact behaviour.

Fortunately, it seems to have been fixed in one of the commits between 1af412bfc5d14634ecc42fc4ad21e4707cc33da4 and the current (0b05f01408bb9df5a558123486918315421903f5).

I have not sat down to figure out exactly what caused this behaviour, but I wanted to post it here for posterity

Thanks!

**Comment by binghe** [comment]
Hi, considering you're using single socket, my recent optimization (only in `master`) in df1f86c11d1f597cb9debc6c7aa0a8ba84094a63 could be the one which occasionally fixed your issue. I hope you can stay at `master` branch (without enabling IOlib backend) and confirm if your problem is really fixed. Thanks.

**Comment by Zulu-Inuoe** [comment]
Apologies for leaving this open this long, but as of version 8.0 this has been fixed (though I never did go back through to find which commit actually fixed it).
So I wanted to come back and close this issue to tidy things up.

Thanks!

**Comment by binghe** [comment]
Good to know.
