### ISSUE TITLE
read-sequence on socket stream blocks current thread

### ISSUE THREAD

**Issue by turtle-bazon** [usocket/usocket#47]
Trying to read available data to buffer causes blocking until whole buffer will read. So, using read-sequence is unusable. Without it read operations on socket is far more slow.

**Comment by binghe** [comment]
Hi,

The network I/O API provided by usocket are all so-called "blocking I/O", in general you need to use `WAIT-FOR-INPUT` to check if there're available data to read, then call `READ-SEQUENCE` which reads the available data and returns immediately.

The situation is the same if you directly use blocking I/O of BSD sockets in C, where the non-blocking I/O API is available but much harder to use.

--Chun

**Comment by binghe** [comment]
Another way is to use multi-threading: you should have a dedicated thread calling `READ-SEQUENCE`, while the other threads in your program are not blocked.

**Comment by turtle-bazon** [comment]
Yes, I do wait-for-input and try to read-sequence in buffer. Buffer length is more than incoming data. And read-sequence doesn't read only available data but blocks and wait until there are will be available data to fill buffer. Can I do something that read-sequence read only available number of bytes?

**Comment by binghe** [comment]
I think in this case you can't use `read-sequence` any more. I personally think `wait-for-input` should have a way to tell the user how many bytes are available for read, beside telling just something is available. I'm not an expect in TCP networking (I mostly was working with UDP), but at this level all CL platforms should behave the same, as `read-sequence` is provided by CL standard on any stream, including socket streams.
