### ISSUE TITLE
Warnings of unknown variables when compiling usocket.asd

### ISSUE THREAD

**Issue by drmeister** [usocket/usocket#49]
This code... 
https://github.com/usocket/usocket/blob/master/usocket.asd#L54

Should the package-less symbols be quoted?
```
(defmethod perform ((op test-op) (c (eql (find-system :usocket))))
  (oos 'load-op ':usocket-server)
  (oos 'load-op ':usocket-test)
  (oos 'test-op ':usocket-test))
```

**Comment by binghe** [comment]
So what's your fix?  Does `(find-system ':usocket)` fix the warning? Can you confirm on your CL platform?

**Comment by binghe** [comment]
I have changed that `defmethod` using your version. I still don't know which CL platform are you using. But I think the change is safe, closed this issue. Thanks.
