### ISSUE TITLE
usocket:wait-for-input waits only in the first call

### ISSUE THREAD

**Issue by Hamayama** [usocket/usocket#50]
When socket-or-sockets argument is only one socket,
wait-list is created only once and event object isn't reset.

https://github.com/usocket/usocket/blob/2b92b917cf9bd763492461b5b9814e801d1b063f/usocket.lisp#L348

https://github.com/usocket/usocket/blob/2b92b917cf9bd763492461b5b9814e801d1b063f/backend/sbcl.lisp#L618

So, usocket:wait-for-input waits only in the first call.

I made a workaround for lem editor as follows.
https://github.com/cxxxr/lem/pull/385/files#diff-c197fa296dcb24f88b3bbed4b49452bdR242

But, it might be better to specify the second argument of WSAEnumNetworkEvents.

https://docs.microsoft.com/en-us/windows/desktop/api/winsock2/nf-winsock2-wsaenumnetworkevents

https://github.com/usocket/usocket/blob/2b92b917cf9bd763492461b5b9814e801d1b063f/backend/sbcl.lisp#L727

**Comment by Hamayama** [comment]
Environment:
- Windows 8.1 (64bit)
- SBCL 1.4.2
- usocket 0.8.1

**Comment by Hamayama** [comment]
I made a small example to reproduce.

server:
```
(ql:quickload "usocket-server")
(defvar cnt 0)
(defun tcp-handler (stream) 
  (terpri stream)
  (incf cnt)
  (format t "called ~s~%" cnt))
(usocket:socket-server "127.0.0.1" 10000 #'tcp-handler)
```

client:
```
(ql:quickload "usocket")
(defvar s (usocket:socket-connect "127.0.0.1" 10000))
(loop
  :with cnt := 0
  :do (usocket:wait-for-input s :ready-only t :timeout 5)
      (incf cnt)
      (format t "call ~s~%" cnt))))
```

server displays only "called 1".
client displays many "call X" without waiting.

**Comment by Hamayama** [comment]
Sorry, usocket:socket-server seems to close sockets automatically.
Something other server software is needed.
When server software sends one character to client without close,
the issue is reproduced in my environment.

**Comment by binghe** [comment]
Hi Hamayama, thanks for your detailed issue reports. The SBCL/Windows backend has many native FFI code, which are rarely used (and buggy). I'll analyze your code  ASAP (say, this weekend) and get back to you.

**Comment by binghe** [comment]
Hi Hamayama,

thanks again for reporting this issue. Now I understood the problem. The optimization for single-socket call of WAIT-FOR-INPUT was an optimization, but I didn't know in this case the WSAEvent must be reset for next uses. Previously such resets are not needed, because all created WSAEvent objects are fresh and immediately freed after use.

Now I've committed changes following your idea of setting the 2nd argument of WSAEnumNetworkEvents, for SBCL and LispWorks on Windows.  (I still need to fix ECL on Windows, an maybe other backends)  I hope you can find some time to confirm if the current code base works for you.

--Chun

**Comment by Hamayama** [comment]
Thank you for update.

I tested latest master (722da85) but got a following error.
```
debugger invoked on a TYPE-ERROR in thread
#<THREAD "main thread" RUNNING {10027900C3}>:
  The value
    #<SB-ALIEN-INTERNALS:ALIEN-VALUE :SAP #X00B29800 :TYPE (*
                                                            (SB-ALIEN:SIGNED
                                                             64))>

  is not of type
    (SIGNED-BYTE 64)
  when binding SB-ALIEN::VALUE

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit debugger, returning to top level.

(USOCKET::WSA-ENUM-NETWORK-EVENTS 260 #<SB-ALIEN-INTERNALS:ALIEN-VALUE :SAP #X00WORK-EVENTS (USOCKET::NETWORK-EVENTS (SB-ALIEN:SIGNED 32) :OFFSET 0) (USOCKET::E
   source: (DEFINE-ALIEN-ROUTINE
            ("WSAEnumNetworkEvents" WSA-ENUM-NETWORK-EVENTS) INT
            (SOCKET WS-SOCKET) (EVENT-OBJECT WS-EVENT)
            (NETWORK-EVENTS (* (STRUCT WSA-NETWORK-EVENTS))))
0] 0
```

I changed from `wait-list-%wait` to `os-wait-list-%wait` in the following place.
https://github.com/usocket/usocket/commit/4f23598bf9004109e90fffda950ca9d5c258dd95#diff-e05ae6d502d213edf66637cbe92ae849R734

Then, it works as expected.
(client software waits every time in wait-for-input.)

**Comment by binghe** [comment]
Hi, thanks very much!  I've fixed the remaining type issue. I'll test the LispWorks backend and make a new release, as this serious bug was introduced in version 0.8.0, I can't let it hurt more users.

Consider current issue closed. Thanks again.
