### ISSUE TITLE
Error: The condition Bad address (error #14) during socket creation operation in bind occurred with errno: 0

### ISSUE THREAD

**Issue by BHa2R00** [usocket/usocket#52]
I am trying to run hunchentoot on ccl , and I have tried this demo in hunchentoot document : 
(T482:lisp/ccl/201907271334) # cat 1.lisp
(hunchentoot:start (make-instance 'hunchentoot:easy-acceptor :port 80))
(hunchentoot:define-easy-handler (say-yo :uri "/yo") (name)
  (setf (hunchentoot:content-type*) "text/plain")
  (format nil "Hey~@[ ~A~]!" name))
then I loaded it in ccl :
(T482:lisp/ccl/201907271334) # ./ccl/ppccl64 -I 0.img -l 1.lisp
> Error: The condition Bad address (error #14) during socket creation operation in bind occurred with errno: 0.
> While executing: USOCKET::RAISE-ERROR-FROM-ID, in process listener(1).
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Skip loading "1.lisp"
> Type :? for other options.
1 >

**Comment by binghe** [comment]
Hi,

I see you're using `ppccl64`, so this should be a Clozure CL (which version?) running on native 64-bit PowerPC Mac OS X. Unfortunately USOCKET was never tested on this platform.

But since the error happens immediately after you loaded those code, I guess it's not allowed to bind port 80, even you're using a "root" user.   Could you please try another port like 8080 and see if the error disappears? If it still doesn't work, I'm afraid that you have to resolve this issue by yourself.

--Chun

**Comment by BHa2R00** [comment]
> Hi,
> 
> I see you're using `ppccl64`, so this should be a Clozure CL (which version?) running on native 64-bit PowerPC Mac OS X. Unfortunately USOCKET was never tested on this platform.
> 
> But since the error happens immediately after you loaded those code, I guess it's not allowed to bind port 80, even you're using a "root" user. Could you please try another port like 8080 and see if the error disappears? If it still doesn't work, I'm afraid that you have to resolve this issue by yourself.
> 
> --Chun

I am using Clozure CL 1.10 on IBM power6 p520 Linux-4.19.44 , and I have tried other ports (90,91,150,151,180,4000,7001,8000,8080,9001....) the problem remains the same , and iptable have been switched off . But I see that the function raise-error-from-id is defined in usocket/backend/openmcl.lisp : 
(defun raise-error-from-id (condition-id socket real-condition)
  (let ((usock-err (cdr (assoc condition-id +openmcl-error-map+))))
    (if usock-err
        (error usock-err :socket socket)
      (error 'unknown-error :socket socket :real-error real-condition))))
and "Bad adress" (error #14) is defined in /usr/include/asm-generic/errno-base.h : 
then , ...

**Comment by binghe** [comment]
I can try to make a Linux PPC64 box (by QEmu) to see if the issue is reproducible there. So far you have to try to figure out the issue by yourself. One possible way is to see if you can just create a simple TCP listener using CCL's native socket API, because currently I think the error happens immediately after Hunchentoot tries to listen on a TCP port.

**Comment by binghe** [comment]
Turning to GNU CLISP or ECL is also an option, if your sole purpose is to run a Lisp-based Web server.

**Comment by BHa2R00** [comment]
> Turning to GNU CLISP or ECL is also an option, if your sole purpose is to run a Lisp-based Web server.

CLISP and ECL are available on this platform , but they are much slower than SBCL and CCL , and beside web server , I need it to do some other things .

**Comment by BHa2R00** [comment]
> Turning to GNU CLISP or ECL is also an option, if your sole purpose is to run a Lisp-based Web server.

The CPU of this machine is a little bit different with that in QEMU , it's opcode is big endian .

**Comment by binghe** [comment]
> > Turning to GNU CLISP or ECL is also an option, if your sole purpose is to run a Lisp-based Web server.
> 
> The CPU of this machine is a little bit different with that in QEMU , it's opcode is big endian .

Which Linux distribution (and version) are you using?  I've learnt to use QEMU, but after installing a Debian 10.0 ppc64el, CCL 1.10 doesn't run, rebuilding from sources also doesn't work.  But since you can run CCL, now I guess the ppc64 version of Clozure CL must be also big endian.  But Debian doesn't have a big endian ppc64 version at all.

**Comment by BHa2R00** [comment]
> > > Turning to GNU CLISP or ECL is also an option, if your sole purpose is to run a Lisp-based Web server.
> > 
> > 
> > The CPU of this machine is a little bit different with that in QEMU , it's opcode is big endian .
> 
> Which Linux distribution (and version) are you using? I've learnt to use QEMU, but after installing a Debian 10.0 ppc64el, CCL 1.10 doesn't run, rebuilding from sources also doesn't work. But since you can run CCL, now I guess the ppc64 version of Clozure CL must be also big endian. But Debian doesn't have a big endian ppc64 version at all.

Yes , the CPU is big edain (IBM POWER6) ppc64 , and the Linux distribution is Gentoo . I have found that the CCL 1.10 can't be build directly from sources , so I have to change "lisp-kernel/platform-linuxppc64.h" here in line  23 : 
#include "sys/ucontext.h"

typedef struct ucontext_t ExceptionInformation;

then CCL runtime can be built successfully .

**Comment by BHa2R00** [comment]
OK , I find that the problem lies with CCL ,
(T482:lisp/ccl/201907271334) # cat 4.lisp 
(WITH-OPEN-SOCKET (socket :LOCAL-PORT 6667 
                          :LOCAL-HOST "localhost" 
                          :CONNECT :PASSIVE 
                          :REUSE-ADDRESS t)
  (let ((stream (ACCEPT-CONNECTION socket :wait t)))
    (format stream "hello from server.~%")
    (finish-output stream)
    stream))
(T482:lisp/ccl/201907271334) # ./ccl/ppccl64 -l 4.lisp
> Error: Bad address (error #14) during socket creation operation in bind
> While executing: SOCKET-ERROR, in process listener(1).
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Skip loading "4.lisp"
> Type :? for other options.
1 >

**Comment by binghe** [comment]
I think it's still possible that, the TCP port 6667 is already used. Try to use `telnet localhost 6667` to eliminate this (small) possibility.

Also, I think you're not the owner of that POWER8 machine, and it's possible that SELinux or something else may be configured by the system administrator, and the program `ppccl64` may not have privileges to listen on any TCP port.

**Comment by BHa2R00** [comment]
> I think it's still possible that, the TCP port 6667 is already used. Try to use `telnet localhost 6667` to eliminate this (small) possibility.
> 
> Also, I think you're not the owner of that POWER8 machine, and it's possible that SELinux or something else may be configured by the system administrator, and the program `ppccl64` may not have privileges to listen on any TCP port.

I am the owner of this machine , I brought it and install the system on myself . I just didn't install the selinux and disabled it in kernel . There are only root user on the machine and I have tried many ports and checked them by using telnet,netstat and lsof . I am sure that none of them were occupied . And I have posted another issue : https://github.com/Clozure/ccl/issues/220

**Comment by binghe** [comment]
Is the recent SBCL ppc64 port [1] a big endian one? Have you tried it?

[1] https://sourceforge.net/p/sbcl/mailman/message/36748655/

**Comment by BHa2R00** [comment]
> Is the recent SBCL ppc64 port [1] a big endian one? Have you tried it?
> 
> [1] https://sourceforge.net/p/sbcl/mailman/message/36748655/

Yes , I have tried it . I open the nfs and mount the sbcl source directory under the x86 machine , then I build host-1,2 on x86 and target-1,2 on ppc64 , eventually when I was running make-target-2.sh on ppc64 , it went into LDB : 

T482 /home/a/project/lisp/sbcl/sbcl-1.5.6 # sh make-target-2.sh 
//entering make-target-2.sh
//doing warm init - compilation phase
This is SBCL 1.5.6, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
Missing required foreign symbol 'alloc_tramp'
COLD-INIT... (Length(TLFs)= 9779)
fatal error encountered in SBCL pid 14004:
no handler for signal 4 in interrupt_handle_now(..)


Welcome to LDB, a low-level debugger for the Lisp runtime environment.
ldb>

**Comment by binghe** [comment]
Well, maybe waiting a few days SBCL people will upload some binaries (they actually provided both big and little endian versions) so that you don't need to do cross-compiling any more.  I still cannot get a working ppc64 (big endian) Linux on QEMU, but I do have a working Debian ppc64le Linux box, and I'll try last SBCL ppc64el there.

Good luck (for both us).

**Comment by BHa2R00** [comment]
> Well, maybe waiting a few days SBCL people will upload some binaries (they actually provided both big and little endian versions) so that you don't need to do cross-compiling any more. I still cannot get a working ppc64 (big endian) Linux on QEMU, but I do have a working Debian ppc64le Linux box, and I'll try last SBCL ppc64el there.
> 
> Good luck (for both us).

If you need ppc64 (big endian) Linux , I can provide you ssh , vnc or something else of this machine if necessary. 
Good luck.

**Comment by binghe** [comment]
> If you need ppc64 (big endian) Linux , I can provide you ssh , vnc or something else of this machine if necessary.
> Good luck.

Thanks. Actually if you met again any issue when using usocket, when you have a working SBCL ppc64 version, I'll be glad to help by login into your machine by SSH for debugging purposes.

Chun
