### ISSUE TITLE
wait-for-input fails to honor :ready-only t

### ISSUE THREAD

**Issue by Reepca** [usocket/usocket#57]
wait-for-input is broken whenever `:ready-only t` is specified. This is because `single-socket-p` is defined to be `(atom socket-or-sockets)` _whenever wait-for-input is invoked_. This includes when it is invoked recursively to replace the list-of-usockets with a `wait-list`. But a `wait-list` is always an atom. Thus, everything after the `(unless (wait-list-p socket-or-sockets) ...)` form will always have single-socket-p true, _regardless of the number of wait-list-waiters_. 

Example: suppose `socket-or-sockets` is initially `(a b c d)`, all sockets, and `ready-only` is `t`. As it's not a `wait-list`, and not null, `wait-for-input` will be invoked recursively with a `wait-list` with four `wait-list-waiters`. This time `single-socket-p` will be `t`, because a `wait-list` is an atom. It will invoke `listen` and `wait-for-input-internal` and set the socket states accordingly. Let's suppose that only `d` has been found to have input available. When it comes time to return the list of ready sockets, `single-socket-p` will still be `t`, and since the first socket in the list, `a`, isn't ready, `nil` will be returned.

One fix for this would be to replace

    &aux (single-socket-p (atom socket-or-sockets))
with

    &aux 
    (single-socket-p (or (and (wait-list-p socket-or-sockets) 
                              (= (length (wait-list-waiters socket-or-sockets)) 1))
	                 (usocket-p socket-or-sockets)))

This would fail to consider a list with a single usocket as a single socket, but so does the current code.

**Comment by binghe** [comment]
Hi,

thanks for the bug report, I appreciate the details and deep analysis.

I think the key problem is that, my previous use of `atom` failed to distinguish between a single `usocket` and a `wait-list`. So, if I change `atom` to `usocket-p`, that should resolve the problem.   A problem of your proposed fix is: if the user created a single-socket wait list by himself and passed it to `wait-for-input`, all special code for the case of `single-socket-p` shouldn't be triggered at all, but in fact it's not true (in the last a few lines of `wait-for-input`).

Let me know if you still have concerns. I'm going to push a new release in a few days, for this important fixes. Thanks again.

Chun
