### ISSUE TITLE
Need to give initial values to *echo-server*  and *echo-server-port* in test/test-datagram.lisp

### ISSUE THREAD

**Issue by Yehouda** [usocket/usocket#60]
The test go 
  (unless (and *echo-server* *echo-server-port*)
      (start-server))

but *echo-server* and *echo-server-port* are DEFVARed without a value, so they are unbound
and the form above gives an unbound variable error. Initializing
*echo-server* and *echo-server-port* to nil fixes it.

(defvar *echo-server* nil)
(defvar *echo-server-port* nil)

**Comment by binghe** [comment]
Fixed. Will fix the entire regression tests after all your issues are fixed.

**Comment by binghe** [comment]
And Thanks!
