### ISSUE TITLE
+lispworks-error-map+ contains conditions that need fixing

### ISSUE THREAD

**Issue by Yehouda** [usocket/usocket#61]
1) NS-TRY-AGAIN-CONDITION is currently not a sub-class of socket-condition. It actually causes
   an error when RAISE-USOCK-ERR tries to signal it, because it passes :socket which is not
   an acceptable initarg for NS-TRY-AGAIN-CONDITION. That happens to me while running
   the tests of cl+ssl. 

   That seem to me like a "typo". Changing the definition of NS-TRY-AGAIN-CONDITION to 
   inherit from ns-try-again-condition like this:

       (define-usocket-condition-classes
          (ns-try-again-condition)
           (socket-condition))
  
   eliminate the failures in cl+ssl, and didn't change the number of failures in the usocket regression tests. 

2) OUT-OF-MEMORY-ERROR and ALREADY-SHUTDOWN-ERROR are not defined anywhere. I didn't
   see any problem because of these, just noticed these while looking at the error in cl+ssl.

**Comment by varjagg** [comment]
Ran into (1) as well.

**Comment by binghe** [comment]
Hi @Yehouda,

sorry for the long delay... I have fixed the definition of `ns-try-again-condition` in your suggested way on `master`. Can you suggest a patch for addin the missing `OUT-OF-MEMORY-ERROR` and `ALREADY-SHUTDOWN-ERROR` (I have no idea what to fix...)

Regards,

Chun

**Comment by Yehouda** [comment]
That item was wrong actually. They are defined by the **define-usocket-condition-classes** form in condition.lisp.

**Comment by binghe** [comment]
> That item was wrong actually. They are defined by the **define-usocket-condition-classes** form in condition.lisp.

Now I see your point. Fixed in `master`. Thanks!
