### ISSUE TITLE
LispWorks specific: need to ensure callers of RAISE-USOCK-ERR return the right values(s)

### ISSUE THREAD

**Issue by Yehouda** [usocket/usocket#62]
backend/lispworks.lisp

The LispWorks version of RAISE-USOCK-ERR in some cases calls SIGNAL
rather than ERROR, which means it may return, returning the result of
SIGNAL, which is nil. That may cause a problem if the caller expects 
specific return values.

I actually got an error because PLUSP was called with nil from  UDP-EVENT-LOOP
(in server.lisp), presumably because the second return value of SOCKET-RECEIVE
was nil. That can happen if SOCKET-RECEIVE ended calling RAISE-USOCK-ERR in the
end and then RAISE-USOCK-ERR returns. SOCKET-RECEIVE needs to make sure it return
the expected values when RAISE-USOCK-ERR returns. 

SOCKET-SEND probably also needs fixing. 

The others calls look ok to return nil. 

The error occurred in an idle image, in the process that was created by SOCKET-SERVER,
some time (probably few hours)  after I ran the regression tests of usocket, so it is
not easily reproducible.

**Comment by binghe** [comment]
thanks.  I slightly changed the code of `SOCKET-SEND` and `SOCKET-RECEIVE` to make sure the NIL coming from `raise-usock-error` is not returned. d0f34586
