### ISSUE TITLE
LispWorks specific:  socket-accept should check is actually got  a socket

### ISSUE THREAD

**Issue by Yehouda** [usocket/usocket#63]
**socket-accept** for  **stream-server-usocket** in backend/lispworks.lisp needs to check that the socket it got from **comm::accept-connection-to-socket** or **comm::get-fd-from-socket** is not NIL, because both of these can return NIL for failures.

What it should do if it is NIL is not obvious. LispWorks has a mechanism that re-tries until some number of consecutive failures, and then closes the accepting socket and tries to re-open it.

Maybe it should take another keyword like :error-handling to tell it what to do. 

At the moment it gets an error of type **usocket:invalid-socket-error** inside the call make-stream-socket.  A minimal change would be to add an accept-error condition and to signal an erro with it.

**Comment by binghe** [comment]
Hi, thanks for the issue report.  I think the main problem is that, when the underlying socket got from `comm::accept-connection-to-socket` or `comm::get-fd-from-socket` is NIL, the error is not correctly captured by `with-mapped-conditions` (from `errno`). For `socket-accept` itself, I think it's better to prevent `invalid-socket-error` and just returns NIL in this case.

I've committed 2d9fc563 for this problem.

**Comment by binghe** [comment]
Closing this issue. Let me know if there's still related problems. Thanks again.
