### ISSUE TITLE
Umlaut domains not found ("bücher.at")

### ISSUE THREAD

**Issue by phmarek** [usocket/usocket#69]
While my browser can resolve `bücher.at`, `USOCKET` can't.

Furthermore, some implementations (or perhaps just the FFI interface) only allow simple strings, so data coming from outsite (JSON, XML, ...) may break:

```lisp
(usocket:get-host-by-name 
  (make-array 9
              :fill-pointer 9
              :element-type 'character
              :initial-contents "bücher.at"))
; The condition The value "bücher.at" is not of type SIMPLE-STRING
;               when binding STRING occurred with errno: 0.
;    [Condition of type USOCKET:UNKNOWN-ERROR]
; 
; Frames:
;   0.  (SB-ALIEN::STRING-TO-C-STRING "bücher.at" :UTF-8) [external]
;   1.  (SB-BSD-SOCKETS:GET-HOST-BY-NAME "bücher.at")
;   2.  (USOCKET:GET-HOSTS-BY-NAME "bücher.at")
;   3.  (USOCKET:GET-HOST-BY-NAME "bücher.at")
```

If would be great if such internal restrictions would be ensured at the lower `USOCKET` border, so that the users don't need to know about them.

Thanks a lot!

**Comment by Akaame** [comment]
To anyone who comes across this issue:

```lisp
(ql:quickload "usocket")
(ql:quickload "idna")

(write 
    (usocket:get-host-by-name
        (idna:to-ascii "bücher.at")))
```

The question to if a socket library should include/depend on a IDNA spec implementation is well beyond my level. CPython handles punycode internally.

Cheers.

**Comment by binghe** [comment]
Thanks for the question and the solution. I feel usocket shouldn't explicitly load "idna" and wrap every call of `get-host-by-name` to `idna:to-ascii` first, thus consider the issue closed without any code change (except for possible documentation changes in the future.)
