### ISSUE TITLE
Build failure on some SBCL versions due to sb-int:broken-pipe 

### ISSUE THREAD

**Issue by avodonosov** [usocket/usocket#81]
Hi.

The `sb-int:broken-pipe` added in f9b1e36 breaks build on some SBCL versions, like 1.3.21: http://cl-test-grid.appspot.com/blob?key=ej35972zl9

Note, on some platforms the default SBCL is even onlder than 1.3: http://www.sbcl.org/platform-table.html

I discovered this isspe only now, because Quicklisp seems punlled new usocket only now.

**Comment by avodonosov** [comment]
For a fix, maybe use reader condition similar to this: https://github.com/lispci/fiveam/commit/e11dee752a8f59065033ef9d60641d4a2f1e8379

**Comment by binghe** [comment]
> For a fix, maybe use reader condition similar to this: [lispci/fiveam@e11dee7](https://github.com/lispci/fiveam/commit/e11dee752a8f59065033ef9d60641d4a2f1e8379)

OK, I have made a similar fix in `master`. But it takes time to propagate to quicklisp dists.  Thanks!
