### ISSUE TITLE
usocket 0.8.4 is broken on windows version 0.8.3 does compile

### ISSUE THREAD

**Issue by etaoinbe** [usocket/usocket#86]
usocket 0.8.4 is broken on windows version 0.8.3 does compile

; caught ERROR:
;   READ error during COMPILE-FILE:
;
;     Symbol "BROKEN-PIPE" not found in the SB-INT package.
;
;       Line: 266, Column: 30, File-Position: 8743
;
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file C:\\Users\\validation\\quicklisp\\dists\\quicklisp\\software\\usocket-0.8.4\\backend\\sbcl.lis
p" {25AFEBB1}>

debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
#<THREAD "main thread" RUNNING {23170329}>:
  COMPILE-FILE-ERROR while
  compiling #<CL-SOURCE-FILE "usocket" "backend" "sbcl">

**Comment by binghe** [comment]
Hi, thanks for the bug report.  What's your SBCL version? and could you please post the contents of your *features*?

**Comment by etaoinbe** [comment]
it was sbcl 1.4 Once I realized this could be the reason I upgraded the sbcl and problem went away

**Comment by binghe** [comment]
Yes, SBCL 1.4 is too old but I aim to support ALL SBCL versions, thus I'm still going to do something regarding this issue. Thanks any way.

**Comment by sabracrolleton** [comment]
I see a bug report https://bugs.launchpad.net/sbcl/+bug/1983355 that sbcl 2.2.7 does not compile 0.8.4 on Windows.

**Comment by binghe** [comment]
> I see a bug report https://bugs.launchpad.net/sbcl/+bug/1983355 that sbcl 2.2.7 does not compile 0.8.4 on Windows.

Thanks for your report. I haven't built SBCL on Windows for a while, but let me do this now.

**Comment by binghe** [comment]
Hi again, I think this is exactly what https://github.com/usocket/usocket/pull/89 was fixing but I haven't made a new release reflecting this fix...

**Comment by binghe** [comment]
Close this issue as I just confirmed that USOCKET 0.8.5 (latest release) works fine on SBCL 1.4.14 where there's no `SB-INT:BROKEN-PIPE` symbol:
```
    ;; learnt from fiveam (suggested by Anton Vodonosov) for early SBCL versions
    #+#.(cl:if (cl:ignore-errors (cl:find-symbol "BROKEN-PIPE" "SB-INT"))
               '(and) '(or))
    (sb-int:broken-pipe . connection-aborted-error)
```
