### ISSUE TITLE
0.8.4 is broken on SBCL 2.2.7 (on Windows) [+solution]

### ISSUE THREAD

**Issue by Mr-Dispatch** [usocket/usocket#88]
Loading on SBCL 2.2.7 (on Windows) errors out with:
```
; Loading "usocket"
;
; caught ERROR:
;   READ error during COMPILE-FILE:
;  
;     Lock on package SB-ALIEN violated when interning HINSTANCE while in package
;     USOCKET.
;   See also:
;     The SBCL Manual, Node "Package Locks"
;  
;     (in form starting at line: 748, column: 0, position: 29389)
```
[ On 2.2.6 it works Ok ]
I asked SBCL guys whether it's a bug on SBCL side, and got the following back:

``` Not really a bug in SBCL. Usocket was using an internal symbol that got removed. ```

The error happens during loading of ``` backend\sbcl.lisp ```, the offending code is (line 760,  think):
``` (sb-alien:define-alien-type ws-event sb-alien::hinstance) ```

**Comment by Mr-Dispatch** [comment]
Seems like hinstance was defined as:
``` (define-alien-type hinstance signed) ```
changing the definition to:
``` (sb-alien:define-alien-type ws-event sb-alien:signed) ```
made  it work again.
Should I prepare a pull-request ?

**Comment by binghe** [comment]
> Seems like hinstance was defined as:
> `(define-alien-type hinstance signed)`
> changing the definition to:
> `(sb-alien:define-alien-type ws-event sb-alien:signed)`
> made it work again.
> Should I prepare a pull-request ?

Hi. Yes, please make the PR. Thanks.

**Comment by Mr-Dispatch** [comment]
PR: https://github.com/usocket/usocket/pull/89

**Comment by Mr-Dispatch** [comment]
Merged, closing.

**Comment by binghe** [comment]
Thanks again.

**Comment by Mr-Dispatch** [comment]
Just a small payback for what all the wonderful peeps provided ;-)
