### ISSUE TITLE
ECL/SBCL and SOCKET-CONNECT timeout

### ISSUE THREAD

**Issue by jetmonk** [usocket/usocket#92]
Reading the source code, I believe that ECL has its own SB-BSD-SOCKETS package mimicking SBCL, so both implementations are supported by sbcl.lisp

SOCKET-OPEN does not support a timeout in ECL.    This timeout is valuable for connecting to an unknown remote host (eg, scanning for IoT devices on a local net).

When I add timeout using BORDEAUX-THREADS:WITH-TIMEOUT, it sometimes works, but sometimes times out too fast.  Running the timeout this way in a separate interrupted thread seems risky and sub-optimal.    The SBCL implementation has its own timeout function in sbcl.lisp that is based on an interrupt, which is _probably_ a bit risky, just like  BORDEAUX-THREADS:WITH-TIMEOUT

So I'm wondering if the following would be a worthy avenue to explore as a change to SOCKET-CONNECT in sbcl.lisp

1. make the socket non-blocking using  (SB-BSD-SOCKETS:NON-BLOCKING-MODE SOCKET) before binding
2. then continue to call (SB-BSD-SOCKETS:SOCKET-CONNECT SOCKET REMOTE PORT), which will now return, being non-blocking
3. then loop/sleep (instead of added complexity of select or poll) at sleep intervals of 10us, 30us, 100us, 300us, 1ms, 10ms, 10ms, 10ms ... until the timeout is exhausted, or a connection happens.   Looping won't slow things down appreciably, if the loop  interval is made smaller than the time that has already been waited (hence, increasing intervals); the sleep will be thread-friendly.  Not sure how to test a connection happening but I think it should be possible.

This would give ECL a timeout for SOCKET-OPEN, and would move SBCL away from the interrupt driven timeout it has, without much more complexity.  poll() or select() would be better, but adding involves some complicated inline C code, unless the existing waiting functions like (READ-SELECT)  can be reused for this.  (Can they?)

Is this a bad idea, or is it something I should try, when I have a chance?

**Comment by binghe** [comment]
Hi,

I admit the current implementation of connection timeout is imperfect, and I think rewriting the related code by using non-blocking socket is in general a good idea (perhaps internally the OS kernel just did the same thing).  Yes, it sounds risky to make such changes but I think we can easily switch between the old and new timeout implementation by using global parameters or even extra keyword parameters of the `SOCKET-CONNECT` function.  I will be happy to review your code if you want to have a try. Thanks.

Chun Tian

**Comment by jetmonk** [comment]
Please see https://github.com/jetmonk/usocket-timeout-sbcl-ccl  for my attempt at this.  The README explains it.

it works for me on OSX and RPi Linux

In short, sockets are set non-blocking, and are tested  for connection status with increasing sleeps using SB-BSD-SOCKET:SOCKET-PEERNAME
