### ISSUE TITLE
0-length payload causes error

### ISSUE THREAD

**Issue by rabuf** [usocket/usocket#93]
https://github.com/usocket/usocket/blob/b720911b232f4f4a1e65bfd86dcf9ebf8c0a8c51/server.lisp#L61

This line checks that the returned data buffer length (contained in `n`)  is positive, however the buffer only contains the data portion of the UDP packet and a 0-length data portion is valid. The result is an erroneous raised error at [L72](https://github.com/usocket/usocket/blob/b720911b232f4f4a1e65bfd86dcf9ebf8c0a8c51/server.lisp#L72).

https://github.com/usocket/usocket/blob/b720911b232f4f4a1e65bfd86dcf9ebf8c0a8c51/server.lisp#L72

**Comment by binghe** [comment]
Thanks
