### ISSUE TITLE
Provide restarts to interactively set host and port when connection error occurs?

### ISSUE THREAD

**Issue by mmontone** [usocket/usocket#99]
Hello,

I think it would be nice to be able to interactively change the host and port when a connection error occurs.
And also a restart for just retrying.

I'm using this patch, but there may be better:

```lisp
(in-package :usocket)

;; Rename current socket-listen definition:
(setf (symbol-function '%socket-listen) #'socket-listen)

;; The new socket-listen with the restarts:
(defun socket-listen (host port  &rest args)
  (let ((socket-host host)
	(socket-port port))
    (loop 
      (restart-case (return (apply #'%socket-listen socket-host socket-port args)) 
	(use-other-port (new-port) 
          :report "Use a different port." 
          :interactive 
          (lambda ()
	    (format *query-io* "Port: ")
            (list (parse-integer (read-line *query-io*))))
	  (setq socket-port new-port))
	(use-other-host (new-host) 
          :report "Use a different host." 
          :interactive 
          (lambda ()
	    (format *query-io* "Host: ")
            (list (read-line *query-io*)))
	  (setq socket-host new-host))
       (retry ()
	  :report "Retry socket connection.")))))
```

What do you think?

**Comment by binghe** [comment]
Hi, this is a good idea. I can put your above function as the common, shared version of `socket-listen` for all backends, and then rename the versions of each backend to something like `socket-listen-internal`.   I believe there's no harm nor performance issues of having this wrapper of `restart-case`.

**Comment by binghe** [comment]
I still like your initial solution. Putting an `with-socket-restarts` wrapper into the `socket-listen` of each backend, will inevitable break the idents or cause a lot of code shifting, while renaming the function name from `socket-listen` to `socket-listen-internal` is much better. The additional function call overhead by creating one more layer is nothing, afterall `socket-listen` is not frequently called (usually just once at the beginning of user program).

Any way, I've commit 36262a18 with your work. Thanks for your contributions! My simple tests (of running up Hunchentoot) show that everything is fine (nothing is broken).

**Comment by mmontone** [comment]
Awesome! Thank you very much!

**Comment by mmontone** [comment]
One last thing: does it make sense to do the same to `socket-connect` ?
